version: 2
executorType: docker
jobs:
  test:
    docker:
      - image: circleci/clojure:lein-2.8.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ .Revision }}

      - run:
          name: Install dependencies
          working_directory: /
          command: sudo apt-get update && sudo apt-get install python-pip && sudo pip install awscli==1.14.38

      - run: curl https://gist.githubusercontent.com/lbradstreet/d9d20e9693f5e32374b3da1f45918e88/raw/9124a9ad4ab1c5ed7a9eb9b29e1dc06f3b03ced9/releasegist.txt >> ~/.ssh/config
      - run: sudo apt-get install rubygems
      - run: sudo gem install asciidoctor coderay

      - run:
          name: add lein voom
          command: mkdir ~/.lein && echo '{:user {:plugins [[lein-voom "0.1.0-20180617_140646-g0ba7ec8"]]}}' > ~/.lein/profiles.clj

      - run:
          name: lein voom build deps
          command: lein voom build-deps

      - run:
          name: test
          command: ./scripts/circle-runner.sh aeron clojure-1.8

      - run:
          name: reflection check
          command: ./scripts/reflection-check.sh

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ .Branch }}-{{ .Revision }}

  release:
    docker:
      - image: circleci/clojure:lein-2.8.1
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9b:cd:16:6a:b9:d9:61:bb:85:1a:7e:db:71:74:eb:7b"
            - "99:c8:54:01:5d:50:f7:a3:c4:80:4e:37:19:df:7b:c7"
            - "d7:03:31:d6:ba:24:f8:0e:fe:51:ee:a0:90:58:18:af"
            - "52:e3:4f:8d:40:91:7d:17:29:af:f2:f8:d7:05:e7:e1"
            - "35:3a:6e:17:67:94:20:d7:3e:8f:ba:46:29:64:3c:d7"
            - "75:c9:32:d5:18:51:14:b7:cb:71:92:ba:5e:31:c6:b5"
            - "e8:c9:1c:3a:40:64:17:d6:2d:81:fc:13:6e:1f:cb:88"
            - "4d:8d:12:99:d6:47:ab:5a:7b:fe:fa:61:86:e4:26:50"
            - "9c:7a:18:46:95:48:c5:53:fe:4c:f3:82:86:10:9f:6e"
            - "bd:16:98:70:b0:f3:50:d9:5a:d8:99:c7:a4:6f:b8:65"
            - "69:d8:eb:37:3e:fe:e3:2a:15:d3:51:e6:ef:a4:44:aa"
            - "5f:b7:c7:d6:1e:79:18:d2:5d:a3:04:16:41:6a:a9:bd"
            - "ba:0a:36:d5:21:a8:14:9f:1b:aa:9b:4d:78:b5:a4:ce"
            - "1c:fa:86:05:e9:1b:81:69:35:9e:ea:83:90:7e:af:f2"
            - "c0:e0:37:79:79:3c:b8:6d:f8:8e:60:d3:aa:1c:9c:92"
            - "c9:c2:ef:1a:87:56:c8:3f:73:68:1b:e3:8a:4a:46:7b"
            - "e1:23:8c:24:d1:c1:8c:91:41:91:0e:45:65:7e:ed:99"
            - "13:e2:cb:53:e5:84:44:a5:c4:6f:51:ec:54:26:08:90"
            - "6c:d5:20:a0:a4:ec:a6:3b:db:87:b3:2a:c3:ae:37:a7"
            - "58:f5:ca:c0:5d:62:b0:95:37:73:20:2b:9f:cd:67:75"
            - "c5:61:47:de:2c:42:87:4a:d1:11:ab:14:3b:6e:5c:e1"
            - "40:8c:bb:9b:82:3b:15:b4:95:cb:2f:8b:51:4d:9a:08"
            - "a6:36:b9:1e:be:60:b6:e8:79:f5:cf:f6:de:94:53:29"
            - "88:30:20:65:d3:7f:d3:0a:74:f8:a0:8a:7c:8d:4f:35"
            - "26:56:d5:eb:0c:47:27:d2:8a:b0:68:3e:55:53:1b:b8"
            - "8c:d8:d7:6d:d0:b9:83:81:05:4a:eb:a7:8e:16:a5:8d"
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ .Revision }}
      - run: curl https://gist.githubusercontent.com/lbradstreet/d9d20e9693f5e32374b3da1f45918e88/raw/9124a9ad4ab1c5ed7a9eb9b29e1dc06f3b03ced9/releasegist.txt >> ~/.ssh/config
      - run: sudo apt-get -y update
      - run: sudo apt-get -y upgrade
      - run: sudo apt-get -y install rubygems
      - run: sudo gem install asciidoctor coderay
      - run:
          name: add lein voom
          command: mkdir ~/.lein && echo '{:user {:plugins [[lein-voom "0.1.0-20180617_140646-g0ba7ec8"]]}}' > ~/.lein/profiles.clj
      - run: git config --global user.email "michael.drogalis@onyxplatform.org"
      - run: git config --global user.name "OnyxBot"
      - run: lein deploy
      - run: lein unison update-projects
      - run: lein unison release-projects 0.14.x

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
             branches:
               only: master
