(ns onyx.messaging.protocols.handler)

(defprotocol Handler 
  (prepare-poll! [this])
  (set-replica-version! [this new-replica-version])
  (set-epoch! [this new-epoch])
  (handle-recovery [this message position session-id])
  (handle-messages [this message position])
  (recovered? [this])
  (set-recover! [this recover*])
  (set-recovered! [this])
  (get-recover [this])
  (set-heartbeat! [this])
  (get-heartbeat [this])
  (set-ready! [this sess-id])
  (get-session-id [this])
  (block! [this])
  (unblock! [this])
  (blocked? [this])
  (completed? [this])
  (get-batch [this]))
